# This is the main functions setting
[functions]
  directory = "netlify/functions"

# This block sets a specific timeout for our 'generate' function
[functions.generate]
  timeout = 26

# This redirect setting remains the same
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200